<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>iRoute.Runtime</AssemblyName>
    <RootNamespace>iRoute.Runtime</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Core/iRoute.Contracts/iRoute.Contracts.csproj" />
    <ProjectReference Include="../../Core/iRoute.Core/iRoute.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
