<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>iRoute.Api</AssemblyName>
    <RootNamespace>iRoute.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../iRoute.Contracts/iRoute.Contracts.csproj" />
    <ProjectReference Include="../iRoute.Core/iRoute.Core.csproj" />
    <ProjectReference Include="../iRoute.Runtime/iRoute.Runtime.csproj" />
    <ProjectReference Include="../iRoute.Infrastructure/iRoute.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="iRoute.UnitTests" />
  </ItemGroup>
</Project>
