apiVersion: v1
kind: ServiceAccount
metadata:
  name: iroute-api
  namespace: iroute
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iroute-worker
  namespace: iroute
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iroute-migrate
  namespace: iroute
automountServiceAccountToken: false
