<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/iRoute.Core/iRoute.Core.csproj" />
    <ProjectReference Include="../../src/iRoute.Api/iRoute.Api.csproj" />
    <ProjectReference Include="../../src/iRoute.Infrastructure/iRoute.Infrastructure.csproj" />
    <ProjectReference Include="../../src/iRoute.Runtime/iRoute.Runtime.csproj" />
    <ProjectReference Include="../../src/iRoute.Worker/iRoute.Worker.csproj" />
  </ItemGroup>
</Project>
